name: TopupRank
main: Vsrstudio\TopupRank\Main
version: 1.2.0-BETA
api: [5.0.0]
author: VsrStudio
description: TopupRank Sistem
website: https://github.com/VsrStudio
commands:
  topuprank:
    description: Open the rank top-up menu
    permission: topuprank.use
  rankadmin:
    description: Open the rank top-up menu
    permission: topuprank.admin
permissions:
  topuprank.use:
    default: true
  topuprank.admin:
    default: op
