ranks:
  §eELITE:
    price: 15.000
    description: ""
    image: "textures/ui/promo_bee"
  §aVIP:
    price: 20.000
    description: ""
    image: "textures/ui/promo_spider"
  §bMVP:
    price: 30.000
    description: "Rank premium dengan fitur khusus."
    image: "textures/ui/promo_chicken"
  §0Legends:
    price: 40.000
    description: ""
    image: "textures/ui/promo_wolf"
  §1Angel:
    price: 60.000
    description: ""
    image: "textures/ui/promo_creeper"
  §dExCluSive:
    price: 80.000
    description: ""
    image: "textures/ui/realms_key_art"

payment_methods:
  - GoPay
  - DANA
  - OVO

messages:
  rank_purchased: "Terima kasih! Permintaan top-up Anda sedang diproses oleh admin."
  notify_admin: "Pemain %player% telah meminta top-up rank %rank% menggunakan metode %method%."
  invalid_phone: "Nomor telepon tidak valid. Masukkan nomor telepon yang benar."
  invalid_gamertag: "Nama gamertag tidak valid. Masukkan nama yang benar."
  payment_success: "Pembayaran berhasil diproses. Rank %rank% telah diberikan kepada pemain."
  payment_rejected: "Pembayaran ditolak oleh admin."
